// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  04-Aug-2019 at 3:04:27 pm
// ======================================================


import Foundation


class Sheet1 {
    var item0 : String? = nil; // Emp ID
    var item1 : String? = nil; // Prefix (Dr / Prof)
    var item2 : String? = nil; // Name of the Faculty
    var item3 : String? = nil; // School Name
    var item4 : String? = nil; // Building Name             (AB1 /AB2 / ADB / CATEEN Block)
    var item5 : String? = nil; // Floor no
    var item6 : String? = nil; // Main/Annex/New Annex
    var item7 : String? = nil; // Room no
    var item8 : String? = nil; // Cabin no
    var item9 : String? = nil; // Intercom number (4digits)
    var item10 : String? = nil; // Email id
}