// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  04-Aug-2019 at 3:04:27 pm
// ======================================================


import Foundation


private let AUTO_PLIST_SHEET1_PATH = Bundle.main.path(forResource: "Sheet1", ofType: "plist")

private let AUTO_PLIST_SHEET1_KEY_ITEM0 = "item0"   // Emp ID
private let AUTO_PLIST_SHEET1_KEY_ITEM1 = "item1"   // Prefix (Dr / Prof)
private let AUTO_PLIST_SHEET1_KEY_ITEM2 = "item2"   // Name of the Faculty
private let AUTO_PLIST_SHEET1_KEY_ITEM3 = "item3"   // School Name
private let AUTO_PLIST_SHEET1_KEY_ITEM4 = "item4"   // Building Name             (AB1 /AB2 / ADB / CATEEN Block)
private let AUTO_PLIST_SHEET1_KEY_ITEM5 = "item5"   // Floor no
private let AUTO_PLIST_SHEET1_KEY_ITEM6 = "item6"   // Main/Annex/New Annex
private let AUTO_PLIST_SHEET1_KEY_ITEM7 = "item7"   // Room no
private let AUTO_PLIST_SHEET1_KEY_ITEM8 = "item8"   // Cabin no
private let AUTO_PLIST_SHEET1_KEY_ITEM9 = "item9"   // Intercom number (4digits)
private let AUTO_PLIST_SHEET1_KEY_ITEM10 = "item10"   // Email id


class DataManager {

    public static let sharedManager = DataManager()
    init(){}

    private var _sheet1s = [Sheet1]()

    func allSheet1s() -> [Sheet1]{

        if _sheet1s.count > 0 {
            return _sheet1s
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_SHEET1_PATH!) {

            for dict in allDatas {
                guard let dict = dict as? [String: AnyObject] else {continue}

                let sheet1 = Sheet1()
                sheet1.item0 = dict[AUTO_PLIST_SHEET1_KEY_ITEM0] as? String // Emp ID
                sheet1.item1 = dict[AUTO_PLIST_SHEET1_KEY_ITEM1] as? String // Prefix (Dr / Prof)
                sheet1.item2 = dict[AUTO_PLIST_SHEET1_KEY_ITEM2] as? String // Name of the Faculty
                sheet1.item3 = dict[AUTO_PLIST_SHEET1_KEY_ITEM3] as? String // School Name
                sheet1.item4 = dict[AUTO_PLIST_SHEET1_KEY_ITEM4] as? String // Building Name             (AB1 /AB2 / ADB / CATEEN Block)
                sheet1.item5 = dict[AUTO_PLIST_SHEET1_KEY_ITEM5] as? String // Floor no
                sheet1.item6 = dict[AUTO_PLIST_SHEET1_KEY_ITEM6] as? String // Main/Annex/New Annex
                sheet1.item7 = dict[AUTO_PLIST_SHEET1_KEY_ITEM7] as? String // Room no
                sheet1.item8 = dict[AUTO_PLIST_SHEET1_KEY_ITEM8] as? String // Cabin no
                sheet1.item9 = dict[AUTO_PLIST_SHEET1_KEY_ITEM9] as? String // Intercom number (4digits)
                sheet1.item10 = dict[AUTO_PLIST_SHEET1_KEY_ITEM10] as? String // Email id
                _sheet1s.append(sheet1)
            }
        }
        return _sheet1s
    }
}
